### ISSUE TITLE
[Feature Request] Add i18n feature

### ISSUE THREAD

**Issue by QD-lazy-tm** [MrWillCom/rsa-cli#5]
In order to increase usability, I recommend you to add support for other languages like Chinese, Japanese, etc.

**Comment by MrWillCom** [comment]
https://github.com/MrWillCom/rsa-cli/commit/c1086aa6ed5afdae12a42ba4737cd596622fb733 implemented i18n.

**Comment by QD-lazy-tm** [comment]
The feature looks awesome! And I appreciate your fast response.
